### ISSUE TITLE
as Prop in Transition

### ISSUE THREAD

**Issue by dnmct** [bettercart/rescript-headless-ui-react#2]
Hey I'm using your bindings, thanks for that.
How would I express the as prop on the Transition. I'm a bit lost there, since I'm pretty new to rescript

**Comment by danwetherald** [comment]
Hey Dan,

I plan to update these bindings to be more complete and use some more modern tailwind concepts that have only recently been released.

Just pushed up @0.3.0 that adds this prop, let me know if this works out for you.

Just a reminder, `as` is reserved, so the prop will be `as_`.

**Comment by dnmct** [comment]
I tried that as well but when i try to pass a fragment like that `as_={React.Fragment}` I get an error.
```
The variant constructor React.Fragment can't be found.

- If it's defined in another module or file, bring it into scope by:
  - Prefixing it with said module name: TheModule.React.Fragment
  - Or specifying its type:
  let theValue: TheModule.theType = React.Fragment
- Constructors and modules are both capitalized. Did you want the latter?
  Then instead of let foo = Bar, try module Foo = Bar.
```

**Comment by danwetherald** [comment]
Just moved over the prop to a `string`. This should allow you to use it in a similar way to the normal API.

```
as_="div"
````

Just deployed a new version `@0.4.0`

**Comment by dnmct** [comment]
so if I want to use a fragment I can just say `"fragment"`. Because I'm pretty sure that doesnt work with regular js

**Comment by danwetherald** [comment]
I think you might be confused to what the as_ prop does. This tells headless what html tag to use when it renders the wrapper. By default this value is "div".

`
The Transition component will render a div by default, but you can use the as prop to render a different element instead if needed. Any other HTML attributes (like className) can be added directly to the Transition the same way they would be to regular elements.
`

**Comment by dnmct** [comment]
Yeah I'm converting my TS codebase to Rescript and used the Transition as prop as follows: `as={React.Fragment}` to avoid having an additional argument that wraps the stuff in the transition
